[2023-04-12 22:21:13,572] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_v1.extract_data_task manual__2023-04-12T22:21:02.040336+00:00 [queued]>
[2023-04-12 22:21:13,666] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_v1.extract_data_task manual__2023-04-12T22:21:02.040336+00:00 [queued]>
[2023-04-12 22:21:13,669] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-04-12 22:21:13,672] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-04-12 22:21:13,673] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-04-12 22:21:13,804] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): extract_data_task> on 2023-04-12 22:21:02.040336+00:00
[2023-04-12 22:21:13,822] {standard_task_runner.py:52} INFO - Started process 11877 to run task
[2023-04-12 22:21:13,854] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE_v1', 'extract_data_task', 'manual__2023-04-12T22:21:02.040336+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/sp_500_data_processing_dag.py', '--cfg-path', '/tmp/tmpef0c8e8o', '--error-file', '/tmp/tmp6e4ff1ad']
[2023-04-12 22:21:13,867] {standard_task_runner.py:77} INFO - Job 215: Subtask extract_data_task
[2023-04-12 22:21:14,191] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE_v1.extract_data_task manual__2023-04-12T22:21:02.040336+00:00 [running]> on host 7b33c6d8ff37
[2023-04-12 22:21:14,496] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE_v1
AIRFLOW_CTX_TASK_ID=extract_data_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T22:21:02.040336+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T22:21:02.040336+00:00
[2023-04-12 22:21:23,772] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas_datareader/tiingo.py:234: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  return pd.concat(dfs, self._concat_axis)

[2023-04-12 22:21:30,500] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-04-12 22:21:30,545] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 11877. PIDs of all processes in the group: [11877]
[2023-04-12 22:21:30,553] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 11877
[2023-04-12 22:21:30,559] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-04-12 22:21:30,573] {logging_mixin.py:109} INFO - Error while extracting data for ABBV: Task received SIGTERM signal
[2023-04-12 22:22:30,598] {process_utils.py:138} WARNING - process psutil.Process(pid=11877, name='airflow task ru', status='sleeping', started='22:21:12') did not respond to SIGTERM. Trying SIGKILL
[2023-04-12 22:22:30,615] {process_utils.py:75} INFO - Sending the signal Signals.SIGKILL to group 11877
[2023-04-12 22:22:30,671] {process_utils.py:70} INFO - Process psutil.Process(pid=11877, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='22:21:12') (11877) terminated with exit code Negsignal.SIGKILL
[2023-04-12 22:22:30,675] {standard_task_runner.py:135} ERROR - Job 215 was killed before it finished (likely due to running out of memory)
