[2023-03-29 18:47:53,519] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE.extract_data_task manual__2023-03-29T18:46:34.195738+00:00 [queued]>
[2023-03-29 18:47:53,582] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE.extract_data_task manual__2023-03-29T18:46:34.195738+00:00 [queued]>
[2023-03-29 18:47:53,584] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 18:47:53,586] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2023-03-29 18:47:53,587] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 18:47:53,637] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): extract_data_task> on 2023-03-29 18:46:34.195738+00:00
[2023-03-29 18:47:53,649] {standard_task_runner.py:52} INFO - Started process 812 to run task
[2023-03-29 18:47:53,666] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE', 'extract_data_task', 'manual__2023-03-29T18:46:34.195738+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmppxbhcqrq', '--error-file', '/tmp/tmpzm6hd5uj']
[2023-03-29 18:47:53,669] {standard_task_runner.py:77} INFO - Job 179: Subtask extract_data_task
[2023-03-29 18:47:53,860] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE.extract_data_task manual__2023-03-29T18:46:34.195738+00:00 [running]> on host 77208106954d
[2023-03-29 18:47:54,044] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE
AIRFLOW_CTX_TASK_ID=extract_data_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T18:46:34.195738+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T18:46:34.195738+00:00
[2023-03-29 18:47:58,929] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas_datareader/tiingo.py:234: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  return pd.concat(dfs, self._concat_axis)

[2023-03-29 18:49:16,757] {logging_mixin.py:109} INFO - Error while extracting data for BRK.B: Unable to read URL: https://api.tiingo.com/tiingo/daily/BRK.B/prices?startDate=2018-03-30&endDate=2023-03-29&format=json
Response Text:
b'{"detail":"Error: Ticker \'BRK.B\' not found"}'
[2023-03-29 18:49:32,138] {logging_mixin.py:109} INFO - Error while extracting data for BF.B: Unable to read URL: https://api.tiingo.com/tiingo/daily/BF.B/prices?startDate=2018-03-30&endDate=2023-03-29&format=json
Response Text:
b'{"detail":"Error: Ticker \'BF.B\' not found"}'
[2023-03-29 18:57:03,232] {logging_mixin.py:109} INFO - Failed to retrieve data for the following tickers: ['BRK.B', 'BF.B']
[2023-03-29 18:57:06,169] {logging_mixin.py:109} INFO - ingestion from api completed
[2023-03-29 18:58:07,106] {logging_mixin.py:109} INFO - file has been saved at :sp_500_data.csv
[2023-03-29 18:58:07,115] {logging_mixin.py:109} INFO - sp_500_data.csv
[2023-03-29 18:58:07,275] {python.py:175} INFO - Done. Returned value was: None
[2023-03-29 18:58:07,389] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=SP_500_DATA_PIPELINE, task_id=extract_data_task, execution_date=20230329T184634, start_date=20230329T184753, end_date=20230329T185807
[2023-03-29 18:58:07,637] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-29 18:58:07,794] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
