[2023-03-30 01:30:56,781] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_v1.extract_data_task scheduled__2023-03-29T20:31:46.196506+00:00 [queued]>
[2023-03-30 01:30:56,882] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_v1.extract_data_task scheduled__2023-03-29T20:31:46.196506+00:00 [queued]>
[2023-03-30 01:30:56,885] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-30 01:30:56,887] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-03-30 01:30:56,891] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-30 01:30:56,999] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): extract_data_task> on 2023-03-29 20:31:46.196506+00:00
[2023-03-30 01:30:57,031] {standard_task_runner.py:52} INFO - Started process 353 to run task
[2023-03-30 01:30:57,071] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE_v1', 'extract_data_task', 'scheduled__2023-03-29T20:31:46.196506+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/sp_500_data_processing_dag.py', '--cfg-path', '/tmp/tmpdqa5e80d', '--error-file', '/tmp/tmpit52chts']
[2023-03-30 01:30:57,074] {standard_task_runner.py:77} INFO - Job 192: Subtask extract_data_task
[2023-03-30 01:30:57,472] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE_v1.extract_data_task scheduled__2023-03-29T20:31:46.196506+00:00 [running]> on host 3334650b113e
[2023-03-30 01:30:57,939] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE_v1
AIRFLOW_CTX_TASK_ID=extract_data_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T20:31:46.196506+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T20:31:46.196506+00:00
[2023-03-30 01:31:04,788] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas_datareader/tiingo.py:234: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  return pd.concat(dfs, self._concat_axis)

[2023-03-30 01:32:05,910] {logging_mixin.py:109} INFO - Error while extracting data for BRK.B: Unable to read URL: https://api.tiingo.com/tiingo/daily/BRK.B/prices?startDate=2018-03-31&endDate=2023-03-30&format=json
Response Text:
b'{"detail":"Error: Ticker \'BRK.B\' not found"}'
[2023-03-30 01:32:41,092] {logging_mixin.py:109} INFO - Error while extracting data for BF.B: Unable to read URL: https://api.tiingo.com/tiingo/daily/BF.B/prices?startDate=2018-03-31&endDate=2023-03-30&format=json
Response Text:
b'{"detail":"Error: Ticker \'BF.B\' not found"}'
[2023-03-30 01:37:22,470] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-03-30 01:37:22,492] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 353. PIDs of all processes in the group: [353]
[2023-03-30 01:37:22,495] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 353
[2023-03-30 01:37:22,499] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-30 01:37:22,503] {logging_mixin.py:109} INFO - Error while extracting data for PXD: Task received SIGTERM signal
